CREATE TABLE "account" (
	"id" text PRIMARY KEY NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"user_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp,
	"refresh_token_expires_at" timestamp,
	"scope" text,
	"password" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_availability" (
	"id" text PRIMARY KEY NOT NULL,
	"userId" text NOT NULL,
	"dayOfWeek" integer NOT NULL,
	"startTime" text NOT NULL,
	"endTime" text NOT NULL,
	"isAvailable" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_availability_override" (
	"id" text PRIMARY KEY NOT NULL,
	"userId" text NOT NULL,
	"date" date NOT NULL,
	"isAvailable" boolean NOT NULL,
	"startTime" text,
	"endTime" text,
	"reason" text
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_booking" (
	"id" text PRIMARY KEY NOT NULL,
	"hostId" text NOT NULL,
	"eventTypeId" text NOT NULL,
	"guestName" text NOT NULL,
	"guestEmail" text NOT NULL,
	"guestPhone" text,
	"guestNotes" text,
	"startTime" timestamp with time zone NOT NULL,
	"endTime" timestamp with time zone NOT NULL,
	"timezone" text NOT NULL,
	"status" text DEFAULT 'PENDING' NOT NULL,
	"googleEventId" text,
	"meetLink" text,
	"cancelToken" text NOT NULL,
	"rescheduleToken" text NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone NOT NULL,
	CONSTRAINT "pg-drizzle_booking_cancelToken_unique" UNIQUE("cancelToken"),
	CONSTRAINT "pg-drizzle_booking_rescheduleToken_unique" UNIQUE("rescheduleToken")
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_event_type" (
	"id" text PRIMARY KEY NOT NULL,
	"userId" text NOT NULL,
	"title" text NOT NULL,
	"slug" text NOT NULL,
	"durationMinutes" integer NOT NULL,
	"description" text,
	"location" text,
	"color" text DEFAULT '#3B82F6',
	"isActive" boolean DEFAULT true NOT NULL,
	"bookingWindowDays" integer DEFAULT 30 NOT NULL,
	"minimumNoticeHours" integer DEFAULT 24 NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_google_calendar_token" (
	"id" text PRIMARY KEY NOT NULL,
	"userId" text NOT NULL,
	"accessToken" text NOT NULL,
	"refreshToken" text NOT NULL,
	"expiresAt" timestamp with time zone NOT NULL,
	"calendarId" text DEFAULT 'primary' NOT NULL,
	"busyCalendarIds" text[] DEFAULT '{"primary"}',
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone NOT NULL,
	CONSTRAINT "pg-drizzle_google_calendar_token_userId_unique" UNIQUE("userId")
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_profile" (
	"userId" text PRIMARY KEY NOT NULL,
	"username" text NOT NULL,
	"bio" text,
	"avatarUrl" text,
	"timezone" text DEFAULT 'Europe/Warsaw' NOT NULL,
	"isVisibleOnHome" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone NOT NULL,
	CONSTRAINT "pg-drizzle_profile_username_unique" UNIQUE("username")
);
--> statement-breakpoint
CREATE TABLE "session" (
	"id" text PRIMARY KEY NOT NULL,
	"expires_at" timestamp NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" text NOT NULL,
	CONSTRAINT "session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean NOT NULL,
	"image" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	CONSTRAINT "user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp,
	"updated_at" timestamp
);
--> statement-breakpoint
ALTER TABLE "account" ADD CONSTRAINT "account_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_availability" ADD CONSTRAINT "pg-drizzle_availability_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_availability_override" ADD CONSTRAINT "pg-drizzle_availability_override_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_booking" ADD CONSTRAINT "pg-drizzle_booking_hostId_user_id_fk" FOREIGN KEY ("hostId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_booking" ADD CONSTRAINT "pg-drizzle_booking_eventTypeId_pg-drizzle_event_type_id_fk" FOREIGN KEY ("eventTypeId") REFERENCES "public"."pg-drizzle_event_type"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_event_type" ADD CONSTRAINT "pg-drizzle_event_type_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_google_calendar_token" ADD CONSTRAINT "pg-drizzle_google_calendar_token_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_post" ADD CONSTRAINT "pg-drizzle_post_createdById_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_profile" ADD CONSTRAINT "pg-drizzle_profile_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "session_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "availability_user_id_idx" ON "pg-drizzle_availability" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "availability_override_user_id_idx" ON "pg-drizzle_availability_override" USING btree ("userId");--> statement-breakpoint
CREATE UNIQUE INDEX "availability_override_user_date_idx" ON "pg-drizzle_availability_override" USING btree ("userId","date");--> statement-breakpoint
CREATE INDEX "booking_host_id_idx" ON "pg-drizzle_booking" USING btree ("hostId");--> statement-breakpoint
CREATE INDEX "booking_event_type_id_idx" ON "pg-drizzle_booking" USING btree ("eventTypeId");--> statement-breakpoint
CREATE INDEX "booking_start_time_idx" ON "pg-drizzle_booking" USING btree ("startTime");--> statement-breakpoint
CREATE INDEX "booking_status_idx" ON "pg-drizzle_booking" USING btree ("status");--> statement-breakpoint
CREATE INDEX "event_type_user_id_idx" ON "pg-drizzle_event_type" USING btree ("userId");--> statement-breakpoint
CREATE UNIQUE INDEX "event_type_user_slug_idx" ON "pg-drizzle_event_type" USING btree ("userId","slug");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "pg-drizzle_post" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "name_idx" ON "pg-drizzle_post" USING btree ("name");--> statement-breakpoint
CREATE UNIQUE INDEX "profile_username_idx" ON "pg-drizzle_profile" USING btree ("username");